version: '3'
services:
  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - microservices-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CATALOG_SERVICE_URL=http://catalog-service:8081
    depends_on:
      - catalog-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
